#ifndef LAYER_PARAMETER_H
#define LAYER_PARAMETER_H

#define YOLO_FOLD_TOTAL_CHANNEL ((30+3)/8)
#define MAX_KERNEL_NUM 64
#define YOLO_INPUT_HEIGHT 5
#define YOLO_INPUT_WIDTH 5
#define MAX_FOLD_CH_BIT (9-2+1)
#endif
