#ifndef LAYER_PARAMETER_H
#define LAYER_PARAMETER_H

#define STREAM_TX_SIZE 10
#define MAX_CH_BIT (9+1)
#define MAX_FOLD_CH_BIT (9-2+1)
#define MAX_KERNEL_NUM 64
#define MAX_INPUT_CH 64
#define MAX_LINE_BUFF_WIDTH (640+2)
#define MAX_KERNEL_DIM 3

#endif
